/**
 * Cookie Manager - Background Service Worker
 * Handles message routing, context menus, and cookie change events
 */

// ============================================================================
// Cookie Operations (inline to avoid module loading issues in MV3)
// ============================================================================

const CookieOps = {
    async getAll(url) {
        try {
            const domain = new URL(url).hostname;
            return await chrome.cookies.getAll({ domain });
        } catch (error) {
            console.error('[ServiceWorker] Error getting cookies:', error);
            return [];
        }
    },

    async set(cookie) {
        try {
            const { domain, ...rest } = cookie;
            const cleanDomain = domain.startsWith('.') ? domain.slice(1) : domain;
            const url = `http${cookie.secure ? 's' : ''}://${cleanDomain}${cookie.path || '/'}`;

            return await chrome.cookies.set({
                url,
                domain,
                ...rest
            });
        } catch (error) {
            console.error('[ServiceWorker] Error setting cookie:', error);
            return null;
        }
    },

    async remove(url, name) {
        try {
            return await chrome.cookies.remove({ url, name });
        } catch (error) {
            console.error('[ServiceWorker] Error removing cookie:', error);
            return null;
        }
    },

    async clearDomain(domain) {
        try {
            const cookies = await chrome.cookies.getAll({ domain });
            let count = 0;

            for (const cookie of cookies) {
                const cookieDomain = cookie.domain.startsWith('.')
                    ? cookie.domain.slice(1)
                    : cookie.domain;
                const url = `http${cookie.secure ? 's' : ''}://${cookieDomain}${cookie.path}`;
                await chrome.cookies.remove({ url, name: cookie.name });
                count++;
            }

            return count;
        } catch (error) {
            console.error('[ServiceWorker] Error clearing domain:', error);
            return 0;
        }
    },

    toJSON(cookies) {
        return JSON.stringify(cookies, null, 2);
    },

    toNetscape(cookies) {
        const lines = ['# Netscape HTTP Cookie File', '# Generated by Cookie Manager (zovo.one)'];

        for (const c of cookies) {
            const httpOnly = c.httpOnly ? '#HttpOnly_' : '';
            const domain = c.domain.startsWith('.') ? c.domain : `.${c.domain}`;
            const flag = c.domain.startsWith('.') ? 'TRUE' : 'FALSE';
            const secure = c.secure ? 'TRUE' : 'FALSE';
            const expiry = c.expirationDate ? Math.floor(c.expirationDate) : '0';

            lines.push(`${httpOnly}${domain}\t${flag}\t${c.path}\t${secure}\t${expiry}\t${c.name}\t${c.value}`);
        }

        return lines.join('\n');
    }
};

// ============================================================================
// Storage Operations
// ============================================================================

const STORAGE_DEFAULTS = {
    readOnlyMode: false,
    protectedDomains: []
};

async function getSettings() {
    try {
        const result = await chrome.storage.local.get(STORAGE_DEFAULTS);
        return { ...STORAGE_DEFAULTS, ...result };
    } catch {
        return STORAGE_DEFAULTS;
    }
}

async function isProtected(domain) {
    const settings = await getSettings();
    return settings.protectedDomains.some(d => domain.endsWith(d));
}

// ============================================================================
// Message Handler
// ============================================================================

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    handleMessage(message).then(sendResponse);
    return true; // Indicates async response
});

async function handleMessage(message) {
    const { action, payload } = message;

    console.log('[ServiceWorker] Received message:', action);

    try {
        switch (action) {
            case 'GET_COOKIES':
                return await CookieOps.getAll(payload.url);

            case 'SET_COOKIE': {
                const settings = await getSettings();
                const domain = payload.domain.startsWith('.')
                    ? payload.domain.slice(1)
                    : payload.domain;

                if (settings.readOnlyMode) {
                    return { error: 'Read-only mode is enabled' };
                }

                if (await isProtected(domain)) {
                    return { error: 'Domain is protected' };
                }

                const result = await CookieOps.set(payload);
                return result || { error: 'Failed to set cookie' };
            }

            case 'DELETE_COOKIE': {
                const settings = await getSettings();

                if (settings.readOnlyMode) {
                    return { error: 'Read-only mode is enabled' };
                }

                return await CookieOps.remove(payload.url, payload.name);
            }

            case 'CLEAR_DOMAIN': {
                const settings = await getSettings();

                if (settings.readOnlyMode) {
                    return { error: 'Read-only mode is enabled' };
                }

                return await CookieOps.clearDomain(payload.domain);
            }

            case 'EXPORT_COOKIES': {
                const cookies = await CookieOps.getAll(payload.url);
                if (payload.format === 'netscape') {
                    return CookieOps.toNetscape(cookies);
                }
                return CookieOps.toJSON(cookies);
            }

            case 'GET_SETTINGS':
                return await getSettings();

            default:
                return { error: 'Unknown action' };
        }
    } catch (error) {
        console.error('[ServiceWorker] Message handler error:', error);
        return { error: error.message };
    }
}

// ============================================================================
// Context Menu
// ============================================================================

function setupContextMenu() {
    // Clear existing menus first (defensive pattern from Zovo framework)
    chrome.contextMenus.removeAll(() => {
        // Suppress any error from removeAll
        void chrome.runtime.lastError;

        chrome.contextMenus.create({
            id: 'clear-site-cookies',
            title: 'Clear cookies for this site',
            contexts: ['page']
        }, () => {
            // Suppress duplicate ID error if it occurs
            void chrome.runtime.lastError;
        });

        chrome.contextMenus.create({
            id: 'separator-1',
            type: 'separator',
            contexts: ['page']
        }, () => void chrome.runtime.lastError);

        chrome.contextMenus.create({
            id: 'open-cookie-manager',
            title: 'Open Cookie Manager',
            contexts: ['page']
        }, () => void chrome.runtime.lastError);
    });
}

chrome.contextMenus.onClicked.addListener(async (info, tab) => {
    if (!tab?.url || tab.url.startsWith('chrome://')) return;

    const domain = new URL(tab.url).hostname;

    switch (info.menuItemId) {
        case 'clear-site-cookies': {
            const settings = await getSettings();

            if (settings.readOnlyMode) {
                chrome.notifications.create({
                    type: 'basic',
                    iconUrl: '/assets/icons/icon-128.png',
                    title: 'Cookie Manager',
                    message: 'Read-only mode is enabled. Disable it to clear cookies.'
                });
                return;
            }

            const count = await CookieOps.clearDomain(domain);

            chrome.notifications.create({
                type: 'basic',
                iconUrl: '/assets/icons/icon-128.png',
                title: 'Cookies Cleared',
                message: `Removed ${count} cookie${count !== 1 ? 's' : ''} from ${domain}`
            });
            break;
        }

        case 'open-cookie-manager':
            chrome.action.openPopup();
            break;
    }
});

// ============================================================================
// Cookie Change Listener
// ============================================================================

chrome.cookies.onChanged.addListener((changeInfo) => {
    // Log cookie changes for debugging
    const { removed, cookie, cause } = changeInfo;
    console.log('[ServiceWorker] Cookie changed:', {
        action: removed ? 'removed' : 'set',
        name: cookie.name,
        domain: cookie.domain,
        cause
    });
});

// ============================================================================
// Installation & Startup
// ============================================================================

chrome.runtime.onInstalled.addListener((details) => {
    console.log('[ServiceWorker] Installed:', details.reason);

    setupContextMenu();

    // Initialize default settings on first install
    if (details.reason === 'install') {
        chrome.storage.local.set(STORAGE_DEFAULTS);
    }
});

chrome.runtime.onStartup.addListener(() => {
    console.log('[ServiceWorker] Startup');
    setupContextMenu();
});

// Initial setup
setupContextMenu();

console.log('[ServiceWorker] Cookie Manager initialized');
